app-config:
  security:
    token:
      secret: GR@BSK1

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/autenticacao
    username: root
    password: 1234

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false