spring:
  profiles.active: dev
  application.name: auth-api

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

secure:
  jwt:
    secret: test-123321