spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
    platform: postgres
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: none
      database: postgresql